---

variables:
  UTIL_FLAKE: git+ssh://git@tsa04.isa.ru/util/nix
  BUILD_FLAKE: "${UTIL_FLAKE}#build"
  DOCKER_FLAKE: "${UTIL_FLAKE}#buildDocker"

stages:
  - build
  - build-docker-image


build:
  stage: build
  rules:
    - if: $CI_SERVER_HOST == "tsa04.isa.ru"

  script:
    - nix run "$BUILD_FLAKE" -- -S -i . -C semvectors-doc-enc
  artifacts:
    reports:
      # build.env is created by BUILD_FLAKE when -S switch is presented
      dotenv: build.env

  tags:
    - nix

build-docker-image:
  stage: build-docker-image
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[build-docker\]/

  script:
    - nix run "$DOCKER_FLAKE" --
      -i ".#trainDockerImage"
      -u "$CI_REGISTRY_USER"
      -p "$CI_REGISTRY_PASSWORD"
      -r "$CI_REGISTRY"
      -ri "$CI_REGISTRY_IMAGE/train"
      -t "$APP_VERSION"

  tags:
    - nix
