variables:
  BUILD_FLAKE: git+ssh://git@tsa04.isa.ru/util/nix#build

stages:
  - build
  - build-docker-image

build:
  stage: build
  script:
    - nix run "$BUILD_FLAKE" -- -i . -a "$CI_PROJECT_NAME"
  tags:
    - nix

build-docker-image:
  stage: build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[build-docker\]/

  script:
    - nix --verbose --print-build-logs  build  .#dockerImage
    - cp -fL result $(basename $(readlink -f result))

  artifacts:
    paths:
      - "*doc_enc.tar.gz"
    expire_in: 42 seconds

  tags:
    - nix
