defaults:
  - base_sent_batches_config

async_generators: 2
batch_generator_conf:
  input_dir: /home/dvzubarev/data/paral_data/undata0/mini
  batch_size: 128
  dont_use_hns: true
  dont_use_dups: true
