---

hydra:
  job:
    chdir: true
defaults:
  - base_config
  - doc_encoder: basic
  - doc_matching: full
  - doc_retrieval: full
  - sent_retrieval: full
  - bench: basic
  - _self_

cache_embeddings: false
