# @package _global_
defaults:
  - /base_classif_config
  - _self_

model_path: >-
  /train/init_models/distilbert.pt
train_meta_path: >-
    /train/data/finetune_classif/patents-ruen/train.csv
dev_meta_path: >-
    /train/data/finetune_classif/patents-ruen/dev.csv
test_meta_path: >-
    /train/data/finetune_classif/patents-ruen/test.csv
data_dir: >-
    /train/data/finetune_classif/ru_patents_dataset.segmented
use_gpu: 0
async_batch_gen: 4
lr: 0.00002

eval_every: 5000
max_updates: 80_000
max_sents: 1024
max_tokens: 19000
bucket_multiplier: 4
truncate_long_docs: true
dropout: 0.4
