---

hydra:
  job:
    chdir: true

defaults:
  - base_config
  - job_logging: default
  - batches: mini
  - trainer: full
  - trainer/optim: basic_adam
  - text_proc: default
  - text_proc/tokenizer: sentencepiece
  - model: default
  - model/sent: dual_enc
  - model/sent/encoder: null
  - model/sent_for_doc: null
  - model/fragment: null
  - model/doc: null
  - _self_

verbose: false
