---

defaults:
  - base_config
  - job_logging: default
  - batches: mini
  - trainer: basic
  - text_proc: default
  - text_proc/tokenizer: sentencepiece
  - model: default
  - model/sent: dual_enc
  - model/sent/encoder: lstm
  - model/fragment: lstm
  - model/doc: lstm
  - _self_

verbose: false
