---
defaults:
  - base_batches_config
  - _self_

sents_batch_iterator_conf:
  async_generators: 1
  batch_generator_conf:
    input_dir: /train/data/sents/paral
    batch_size: 256

docs_batch_iterator_conf:
  async_generators: 2
  exclude_datasets:
    - gwiki
  batch_generator_conf:
    input_dir: /train/data/docs
    batch_src_sents_cnt: 4096
