---
defaults:
  - base_batches_config
  - _self_

sents_batch_iterator_conf:
  async_generators: 1
  batch_generator_conf:
    input_dir: /train/data/sents/paral
    batch_size: 64

docs_batch_iterator_conf:
  async_generators: 4
  exclude_datasets:
    - gwiki
  batch_generator_conf:
    input_dir: /train/data/docs
