defaults:
  - base_batches_config

sents_batch_iterator_conf:
  async_generators: 1
  batch_generator_conf:
    input_dir: /train/data/sents
    batch_size: 128
    dont_use_hns: true
    dont_use_dups: true

docs_batch_iterator_conf:
  async_generators: 2
  exclude_datasets:
    - gwiki
  batch_generator_conf:
    input_dir: /train/data/docs
    batch_src_sents_cnt: 256
    max_sents_per_doc: 512
