# @package _global_
defaults:
  - /base_classif_config
  - _self_

max_sents: 2048
max_tokens: 96_000
enable_amp: true
truncate_long_docs: true
async_batch_gen: 1
# lr: 0.00005
lr: 0.0001

classif_module:
  dropout: 0.4

model_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/tuning/trans/doc_trans_full1-9-4/model.pt
use_gpu: 0

train_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/train.csv
dev_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/dev-micro.csv
test_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/test-micro.csv
data_dir: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/data_ru.segmented
save_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/models/classif-grnti-mini-model.pt
# eval_every: 500
# max_updates: 3000

eval_every: 15
max_updates: 50

save_dev_eval_stat: true
try_predictors_on_dev:
  - threshold
  - topk
  - topk_with_threshold
  - gap
threshold_pred_opts:
  intervals:
    - - 0.5
      - 0.8
      - 0.1
    - - 0.9
      - 0.99
      - 0.01
