# @package _global_
defaults:
  - /base_classif_config
  - _self_

max_sents: 2048
max_tokens: 6_000
bucket_multiplier: 1
enable_amp: true
async_batch_gen: 1
# lr: 0.00005
lr: 0.0001

classif_module:
  dropout: 0.4

overrides:
  text_proc:
    auto_tokenizer_max_seq_len: 1024
  doc:
    transformers_torch_fp16: true
    use_adapter: lora
    adapter_kwargs:
      r: 32
      lora_alpha: 32
      bias: lora_only
      target_modules:
        - q_proj
        - v_proj
        - embed_tokens


model_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/models/pretrained/Qwen3-emb-600M-fp32.pt
use_gpu: 0

train_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/train.csv
dev_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/dev-micro.csv
test_meta_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/meta_lvl2-2000-3000-6039/test-micro.csv
data_dir: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/grnti-classif/data_ru.segmented
save_path: >-
  /home/dvzubarev/Workspace/projects/semvectors/finetune-data/models/classif-grnti-mini-model.pt
# eval_every: 500
# max_updates: 3000

eval_every: 40
max_updates: 50
