# @package _global_
defaults:
  - /base_config
  - _self_

trainer:
  max_updates: 3000
  eval_every: 1500
  checkpoint_every: 4000
  switch_tasks_every: 10
  tasks:
    - SENT_RETR
  eval_tasks:
    - SENT_RETR
  debug_iters:
    - 50

model:
  sent:
    cross_device_sample: true


text_proc:
  min_sent_len: 3
  tokenizer:
    vocab_path: /home/dvzubarev/data/paral_data/data4/unigram_96k_from_100M.spm.model

batches:
  sents_batch_iterator_conf:
    batch_generator_conf:
      batch_size: 256
      input_dir: /home/dvzubarev/data/paral_data/undata0/sents-mini
