# @package _global_
defaults:
  - /base_config
  - override /model/sent/encoder: lstm
  - override /model/fragment: null
  - override /model/doc: averaging
  - _self_

trainer:
  max_updates: 3000
  eval_every: 1500
  checkpoint_every: 4000
  switch_tasks_every: 10
  debug_iters:
    - 50

model:
  sent:
    cross_device_sample: true


text_proc:
  tokenizer:
    vocab_path: /home/dvzubarev/data/paral_data/data4/bpe_256k_from_600M.spm.model

combine_datasets_use_text_proc: true

batches:
  sents_batch_iterator_conf:
    batch_generator_conf:
      batch_size: 256
      input_dir: /home/dvzubarev/data/paral_data/undata0/sents-mini

  docs_batch_iterator_conf:
    use_existing_combined_meta: true
    async_generators: 1
    combine_procs_cnt: 7
    # include_datasets:
    #   - ParalWiki
    #   - SimRuWiki
    #   - SimEnSci
    #   - SimEnWiki
    batch_generator_conf:
      input_dir: >-
        /home/dvzubarev/Workspace/projects/semvectors/datasets-data/doc-mini/
      pad_src_sentences: false
      batch_total_sents_cnt: 256
      batch_total_tokens_cnt: 10_000
      # input_dir: /home/dvzubarev/Workspace/projects/semvectors/datasets-data/doc
